datetime <- paste(as.Date(dataDates$Date), dataDates$Time)
dataDates$Datetime <- as.POSIXct(datetime)
with(dataDates, {plot(Global_active_power~Datetime, type="l", ylab="Global Active Power (kilowatts)", xlab="")})
dev.copy(png, file="plot2.png", height=480, width=480)
dev.off()